export const brand = {
  name: 'Mauritius Holidays Direct',
  phone: '0208 732 4444',
  phoneAlt: '0203 514 8222',
  email: 'info@mauritiusholidaysdirect.co.uk',
  address: '123 Travel House, London, SW1A 1AA',
  hours: 'Mon-Fri 9am-6pm | Sat 10am-4pm',
  trustpilotScore: '5.0',
  trustpilotReviews: '1,004',
}

export const navItems = [
  { name: 'Home', href: '/' },
  { name: 'Hotels', href: '/hotels' },
  { name: 'Offers', href: '/offers' },
  { name: 'Explore', href: '/explore' },
  { name: 'Why Us', href: '/why-us' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
]

export const categories = [
  {
    id: 'all-inclusive',
    title: 'All Inclusive',
    subtitle: 'Stress-free luxury holidays',
    description: 'Everything included for a truly relaxing Mauritius experience.',
    propertyCount: 39,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-arranged-rows-pool-9mHVNND9SpbWQ65wzsfnYcAc94fMiv.jpg',
  },
  {
    id: 'honeymoon',
    title: 'Honeymoon',
    subtitle: 'Romantic island escapes',
    description: 'Create unforgettable memories with your partner in paradise.',
    propertyCount: 40,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/beautiful-luxury-outdoor-swimming-pool-hotel-resort-GL2S39UkbjMGQbc1eaCVMXQTMgU3Qw.jpg',
  },
  {
    id: 'family',
    title: 'Family Holidays',
    subtitle: 'Easy, fun & memorable',
    description: 'Family-friendly resorts with kids clubs and activities for all ages.',
    propertyCount: 36,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-umbrellas-placed-row-4T6TQAytUAJ1kXJbt33gEbq2eHTDqw.jpg',
  },
  {
    id: 'wedding',
    title: 'Weddings',
    subtitle: 'Destination celebrations',
    description: 'Say "I do" in one of the world\'s most romantic destinations.',
    propertyCount: 19,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1796325354619cc8226f7866.48916407-b2Zopl9ymzYUwEPOXaqt6qbgotP0o5.jpg',
  },
  {
    id: 'golf',
    title: 'Golf Holidays',
    subtitle: 'Championship fairways',
    description: 'World-class courses with stunning Indian Ocean backdrops.',
    propertyCount: 16,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/leisure-beautiful-health-garden-landscape-buPXhULhorsvsl96kDOHAGToxM2eog.jpg',
  },
  {
    id: 'twin-centre',
    title: 'Twin Centre',
    subtitle: 'Two journeys, one booking',
    description: 'Combine Mauritius with Dubai, Seychelles, or South Africa.',
    propertyCount: 14,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/person-traveling-enjoying-their-vacation-jQr22I5U9Emg9LMyQF04ugo1U81g0D.jpg',
  },
]

export const hotels = [
  {
    id: 'veranda-grand-baie',
    name: 'Veranda Grand Baie',
    slug: 'veranda-grand-baie',
    stars: 4,
    board: 'Bed & Breakfast',
    price: 1299,
    originalPrice: 1640,
    badge: 'Save 25%',
    period: '01 May - 05 Jul 2026',
    nights: 7,
    coast: 'North Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-with-more-than-5-million-visitors-year-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-QvdJTS2p1FN0JOOhHzo91YWDqcYBkw.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-with-more-than-5-million-visitors-year-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-QvdJTS2p1FN0JOOhHzo91YWDqcYBkw.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/light-garden-luxury-pool-nature-K0rejE2eyHMT0IPYvIlZfI9rER1kIk.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-umbrellas-placed-row-4T6TQAytUAJ1kXJbt33gEbq2eHTDqw.jpg',
    ],
    description:
      'Fully renovated in 2023, the charming Veranda Grand Baie Hotel & Spa offers guests the chance to enjoy a relaxing holiday in stunning surroundings. Situated close to the lively Grand Baie village, this fabulous resort sits on a magnificent lagoon, where white sands and thatched beach parasols create an idyllic tropical setting.',
    highlights: ['Renovated in 2023', 'Close to Grand Baie village', 'Magnificent lagoon location', 'Spa & wellness facilities'],
    categories: ['family', 'all-inclusive'],
  },
  {
    id: 'long-beach',
    name: 'Long Beach',
    slug: 'long-beach',
    stars: 5,
    board: 'Half Board',
    price: 1499,
    originalPrice: 2269,
    badge: '2 FREE Nights',
    period: '09 May - 30 Jun 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/leisure-beautiful-health-garden-landscape-buPXhULhorsvsl96kDOHAGToxM2eog.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/leisure-beautiful-health-garden-landscape-buPXhULhorsvsl96kDOHAGToxM2eog.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-arranged-rows-pool-9mHVNND9SpbWQ65wzsfnYcAc94fMiv.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pool-with-palm-trees-sides-byKwAZ6PNPQp70rjuuPcZEybGHgRdn.jpg',
    ],
    description:
      'Long Beach is a magnificent contemporary 5-star resort, blending Mauritian style with an elegant twist. Approximately an hour from the airport, it is positioned on the untamed Eastern coast of Mauritius. Long Beach derives its name from its remarkably long beachfront, pulsating with energy and activity.',
    highlights: ['Contemporary 5-star resort', 'Remarkably long beachfront', 'Eastern coast location', 'Perfect for active travellers'],
    categories: ['honeymoon', 'family'],
  },
  {
    id: 'lux-belle-mare',
    name: 'LUX* Belle Mare',
    slug: 'lux-belle-mare',
    stars: 5,
    board: 'Half Board',
    price: 1799,
    originalPrice: 2349,
    badge: 'Save 25%',
    period: '01 Jun - 30 Jun 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/miami-bayside-landscape-nUiRnuBSzHAqmonmAPglac2i3FVqak.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/miami-bayside-landscape-nUiRnuBSzHAqmonmAPglac2i3FVqak.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/beautiful-luxury-outdoor-swimming-pool-hotel-resort-GL2S39UkbjMGQbc1eaCVMXQTMgU3Qw.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/silhouette-palm-tree-with-umbrella-u1M7JhC4sFDavsv5Rki2kcoqYKh3xP.jpg',
    ],
    description:
      'LUX* Belle Mare invites you to indulge in a haven of tranquility and natural beauty. Set against the backdrop of sparkling turquoise waters and a long stretch of powder-soft white sand, this vibrant resort offers an experience that seamlessly blends island life with contemporary luxury.',
    highlights: ['Powder-soft white sand beach', 'Turquoise waters', 'Contemporary luxury', 'World-class spa'],
    categories: ['honeymoon', 'all-inclusive'],
  },
  {
    id: 'maritim-resort-spa',
    name: 'Maritim Resort & Spa',
    slug: 'maritim-resort-spa',
    stars: 5,
    board: 'All Inclusive',
    price: 1799,
    originalPrice: 2849,
    badge: 'Save 45%',
    period: '01 May - 30 Jun 2026',
    nights: 7,
    coast: 'Northwest Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/san-diego-dawn-early-morning-with-palm-tree-silhouette-Ywk2ArZjkZptlkskQP0acX7ncR0Vfl.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/san-diego-dawn-early-morning-with-palm-tree-silhouette-Ywk2ArZjkZptlkskQP0acX7ncR0Vfl.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/light-garden-luxury-pool-nature-K0rejE2eyHMT0IPYvIlZfI9rER1kIk.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-umbrellas-placed-row-4T6TQAytUAJ1kXJbt33gEbq2eHTDqw.jpg',
    ],
    description:
      'Located in a picturesque private estate along the protected marine park of Turtle Bay, Maritim resort is made for those looking to immerse themselves in the Mauritian experience. Set within a 62 acre historical estate, with a garden that has been named the most beautiful in Mauritius.',
    highlights: ['62 acre historical estate', 'Protected marine park', 'Award-winning gardens', 'Full all-inclusive'],
    categories: ['all-inclusive', 'family'],
  },
  {
    id: 'heritage-awali',
    name: 'Heritage Awali Golf & Spa',
    slug: 'heritage-awali',
    stars: 5,
    board: 'All Inclusive',
    price: 1899,
    originalPrice: 2559,
    badge: 'Family Favourite',
    period: '01 Jun - 30 Jun 2026',
    nights: 7,
    coast: 'South Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-arranged-rows-pool-9mHVNND9SpbWQ65wzsfnYcAc94fMiv.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-arranged-rows-pool-9mHVNND9SpbWQ65wzsfnYcAc94fMiv.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1796325354619cc8226f7866.48916407-b2Zopl9ymzYUwEPOXaqt6qbgotP0o5.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pool-with-palm-trees-sides-byKwAZ6PNPQp70rjuuPcZEybGHgRdn.jpg',
    ],
    description:
      'Nestled along the untouched southern coast of Mauritius, Heritage Awali Golf & Spa Resort invites guests into a world where African-inspired elegance meets Mauritian warmth. Upon arrival, guests are greeted with the rhythmic beats of djembes, setting the tone for an immersive cultural experience.',
    highlights: ['African-inspired elegance', 'Championship golf course', 'World-class spa', 'All-inclusive dining'],
    categories: ['golf', 'family', 'all-inclusive'],
  },
  {
    id: 'the-residence',
    name: 'The Residence Mauritius',
    slug: 'the-residence',
    stars: 5,
    board: 'Half Board',
    price: 1499,
    originalPrice: 2410,
    badge: 'Luxury Pick',
    period: '01 May - 30 Jun 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/beautiful-luxury-outdoor-swimming-pool-hotel-resort-GL2S39UkbjMGQbc1eaCVMXQTMgU3Qw.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/beautiful-luxury-outdoor-swimming-pool-hotel-resort-GL2S39UkbjMGQbc1eaCVMXQTMgU3Qw.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/leisure-beautiful-health-garden-landscape-buPXhULhorsvsl96kDOHAGToxM2eog.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-with-more-than-5-million-visitors-year-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-QvdJTS2p1FN0JOOhHzo91YWDqcYBkw.jpg',
    ],
    description:
      'Situated along the pristine shores of Belle Mare, The Residence Hotel is a sanctuary where time slows, and natural Mauritian beauty envelops you. The whitewashed facades and grand columns evoke a sense of grand, timeless elegance.',
    highlights: ['Colonial elegance', 'Belle Mare beach', 'Butler service', 'Award-winning restaurant'],
    categories: ['honeymoon'],
  },
  {
    id: 'intercontinental',
    name: 'InterContinental Mauritius',
    slug: 'intercontinental',
    stars: 5,
    board: 'Half Board',
    price: 1549,
    originalPrice: 2349,
    badge: 'Premium Location',
    period: '01 Jun - 30 Jun 2026',
    nights: 7,
    coast: 'Northwest Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/light-garden-luxury-pool-nature-K0rejE2eyHMT0IPYvIlZfI9rER1kIk.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/light-garden-luxury-pool-nature-K0rejE2eyHMT0IPYvIlZfI9rER1kIk.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hammocks-umbrellas-placed-row-4T6TQAytUAJ1kXJbt33gEbq2eHTDqw.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/silhouette-palm-tree-with-umbrella-u1M7JhC4sFDavsv5Rki2kcoqYKh3xP.jpg',
    ],
    description:
      'Tucked along the powdery white sands of Balaclava Bay, the InterContinental Resort Mauritius is a sanctuary where Indian Ocean dreams drift into reality. Imagine awakening to the gentle hush of tide against reef, the air rich with frangipani and sea breeze.',
    highlights: ['Balaclava Bay location', 'Private beach', 'Multiple restaurants', 'Kids club'],
    categories: ['family', 'honeymoon'],
  },
  {
    id: 'constance-belle-mare',
    name: 'Constance Belle Mare Plage',
    slug: 'constance-belle-mare',
    stars: 5,
    board: 'Half Board',
    price: 1649,
    originalPrice: 2299,
    badge: 'Golf & Beach',
    period: '08 Jun - 30 Jun 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/miami-bayside-landscape-nUiRnuBSzHAqmonmAPglac2i3FVqak.jpg',
    images: [
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/miami-bayside-landscape-nUiRnuBSzHAqmonmAPglac2i3FVqak.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/san-diego-dawn-early-morning-with-palm-tree-silhouette-Ywk2ArZjkZptlkskQP0acX7ncR0Vfl.jpg',
      'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/pool-with-palm-trees-sides-byKwAZ6PNPQp70rjuuPcZEybGHgRdn.jpg',
    ],
    description:
      'Imagine a place where the dazzling Mauritian east coast meets pure serenity. That is Constance Belle Mare Plage. Here, 2 kilometers of pristine white sand invite you to unwind, a backdrop of 15 hectares of vibrant tropical gardens beckon you to relax.',
    highlights: ['2km white sand beach', '2 championship golf courses', '15 hectares of gardens', '7 restaurants'],
    categories: ['golf', 'family'],
  },
  {
    id: 'shangri-la-le-touessrok',
    name: "Shangri-La's Le Touessrok",
    slug: 'shangri-la-le-touessrok',
    stars: 5,
    board: 'Half Board',
    price: 1949,
    originalPrice: 3029,
    badge: 'Iconic Luxury',
    period: '01 Sep - 11 Sep 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      "A true Mauritian icon, Shangri-La Le Touessrok Resort & Spa awaits on the pristine east coast of Mauritius, offering an unparalleled blend of luxury, tropical beauty and peace. Set against a backdrop of lush, emerald-green mountains and crystal-clear waters.",
    highlights: ['Private islands access', 'Championship golf course', 'CHI The Spa', 'Overwater restaurant'],
    categories: ['honeymoon', 'golf'],
  },
  {
    id: 'one-and-only-le-saint-geran',
    name: 'One&Only Le Saint Geran',
    slug: 'one-and-only-le-saint-geran',
    stars: 5,
    board: 'Half Board',
    price: 2699,
    originalPrice: 3759,
    badge: 'Ultra Luxury',
    period: '03 May - 30 Jun 2026',
    nights: 7,
    coast: 'East Coast',
    image: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      "The truly fabulous One&Only Le Saint Geran is a world-class property that redefines chic. This exquisite resort is tucked away on its own private peninsula, surrounded by 60 acres of lush tropical gardens on the beautiful Mauritian east coast.",
    highlights: ['Private peninsula', '60 acres tropical gardens', 'World-class dining', 'One&Only Spa'],
    categories: ['honeymoon', 'wedding'],
  },
]

export const reviews = [
  {
    id: 1,
    name: 'Patrick & Victoria',
    hotel: "Shangri-La's Le Touessrok Resort & Spa",
    date: '09 Apr 2026',
    quote:
      'We have all had the most wonderful holiday. In fact, it was so good and so memorable, that we have decided to return to the same hotel in Mauritius next year.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Caglayan & Adam',
    hotel: 'La Pirogue',
    date: '09 Apr 2026',
    quote:
      'Special thanks to the team for making everything smooth, warm and stress-free. We had a great experience from start to finish.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Raymond & Gillian',
    hotel: 'Heritage Le Telfair Golf and Wellness Resort',
    date: '06 Apr 2026',
    quote:
      'From arriving in Mauritius until departure your service was excellent. Both taxi drivers were very professional and we had a seamless experience.',
    rating: 5,
  },
  {
    id: 4,
    name: 'Martin & Elaine',
    hotel: 'Maritim Resort & Spa Mauritius',
    date: '06 Apr 2026',
    quote:
      'Excellent service, quick support and great attention to detail throughout the trip. Samir did a fantastic job as always.',
    rating: 5,
  },
]

export const trustBadges = [
  {
    title: 'Outstanding Customer Service',
    description:
      'We know how important it is to be looked after properly, so we have taken the time to get the details right.',
  },
  {
    title: 'Full Protection',
    description:
      'Fully bonded with ATOL, IATA & ABTA giving you the highest protection available in the holiday industry.',
  },
  {
    title: 'Best Price Guarantee',
    description: 'We are a UK based direct sell holiday company so you get the cheapest prices when you book with us.',
  },
  {
    title: 'No Booking Fees',
    description: "We don't charge you an extra fee for booking your holiday with us.",
  },
]

export const airports = [
  'London Heathrow',
  'London Gatwick',
  'Manchester',
  'Birmingham',
  'Edinburgh',
  'Glasgow',
  'Bristol',
  'Newcastle',
]

export const boardTypes = [
  'Room Only',
  'Bed & Breakfast',
  'Half Board',
  'Full Board',
  'All Inclusive',
]


